version: '3'
services:
  php8-app:
    image: php:8.1-alpine
    container_name: php
    volumes:
      - ./mounts/settings/php/etc:/usr/local/etc
    environment:
      - PHP_INI_DIR=/usr/local/etc/php
    ports:
      - 80:80